version: "3.7"
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: php_bothelp
    container_name: bothelp_php
    volumes:
      - "./app:/var/www/app"
      - "./logs/php:/var/log/bothelp"
    networks:
      - bothelp_network
  nginx:
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      target: nginx_bothelp
    container_name: bothelp_nginx
    depends_on:
      - php
    volumes:
      - "./app:/var/www/app"
      - "./logs/nginx/dev:/var/log/nginx/"
    networks:
      - bothelp_network
  redis:
    container_name: bothelp_redis
    image: redis:alpine
    command: ["sh", "-c", "exec redis-server --requirepass 123"]
    volumes:
      - "./redis-data:/var/lib/redis"
    networks:
      - bothelp_network
networks:
  bothelp_network:
    driver: bridge